---
- hosts: elasticsearch_node_1,elasticsearch_node_2
  roles:
    - { role: "ElasticSearch" }

- hosts: elk03_kibana01
  roles:
    - { role: "Kibana" }

- hosts: elk03_logstash01
  roles:
    - { role: "Logstash" }
